language: go
go:
- 1.10.x

services: 
  - docker

install:
- go get gopkg.in/alecthomas/gometalinter.v1
- go get github.com/gordonklaus/ineffassign
- go get github.com/jgautheron/goconst/cmd/goconst
- go get github.com/kisielk/errcheck
- go get github.com/golang/dep/cmd/dep
- dep ensure
script:
- gometalinter.v1 --vendor --disable-all --enable=vet --enable=ineffassign
  --enable=goconst --tests ./...
- go test -v -race ./...
- docker build -f Dockerfile -t betorvs/taberneiro:$COMMIT .

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push betorvs/taberneiro:$COMMIT
