apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slackbot.fullname" . }}
  labels:
{{ include "slackbot.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "slackbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "slackbot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
          - name: SERVER_PORT
            value: "{{ .Values.service.port }}"
          - name: SLACK_CHANNEL_ID
            value: "{{ .Values.slackChannelID }}"
          - name: SLACK_TOKEN
            value: "{{ .Values.slackToken }}"
          - name: SLACK_DIRECT_MESSAGE
            value: "{{ .Values.slackDirectMessage }}"
          - name: SLACK_APP_ID
            value: "{{ .Values.slackChannelID }}"
          - name: SLACK_APP_NAME
            value: {{ .Values.slackAppName }}
          - name: SLACK_MENU_LINK_IMAGE
            value: "{{ .Values.slackMenuLinkImage }}"
          - name: SLACK_SELECT_MENU
            value: "{{ .Values.slackMenuText }}"
          - name: SLACK_IMAGE_TEXT
            value: "{{ .Values.slackImageText }}"
          - name: SLACK_HELLO_MESSAGE
            value: "{{ .Values.slackHelloMessage }}"
          - name: SLACK_SUGGESTION
            value: "{{ .Values.slackSuggestion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /taberneiro/v1/health
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /taberneiro/v1/health
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
